// mapStyles.ts — styles pour skin InDrive minimal (glassmorphism, overlay, bulles)
import { StyleSheet, Platform } from 'react-native';

export const mapStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#FFFFFF',
  },
  map: {
    ...StyleSheet.absoluteFill,
    zIndex: 0,
  },
  topLeftMode: {
    position: 'absolute',
    top: Platform.OS === 'ios' ? 52 : 28,
    left: 12,
    paddingVertical: 6,
    paddingHorizontal: 10,
    borderRadius: 12,
    backgroundColor: 'rgba(255,255,255,0.9)',
    borderWidth: 1,
    borderColor: 'rgba(0,0,0,0.06)',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.06,
    shadowRadius: 12,
    elevation: 8,
    zIndex: 300,
  },
  topLeftText: { fontSize: 13, fontWeight: '700', color: '#111' },
  infoBubble: {
    position: 'absolute',
    left: 24,
    right: 24,
    bottom: 24,
    padding: 12,
    borderRadius: 14,
    backgroundColor: 'rgba(255,255,255,0.95)',
    borderWidth: 1,
    borderColor: 'rgba(0,0,0,0.06)',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.06,
    shadowRadius: 20,
    elevation: 12,
    zIndex: 400,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  infoLeft: { flex: 1, paddingRight: 8 },
  infoTitle: { fontSize: 15, fontWeight: '700', color: '#111' },
  infoSubtitle: { fontSize: 13, color: '#6B7280', marginTop: 4 },
  bubbleActions: { flexDirection: 'row', alignItems: 'center' },
  actionButton: {
    marginLeft: 8,
    paddingVertical: 8,
    paddingHorizontal: 12,
    borderRadius: 10,
    backgroundColor: '#FF6B35',
  },
  actionText: { color: '#fff', fontWeight: '700' },
});
